#!/bin/bash

#
# The BSD 3-Clause License. http://www.opensource.org/licenses/BSD-3-Clause
#
# This file is part of 'mingw-builds' project.
# Copyright (c) 2011,2012, by niXman (i dotty nixman doggy gmail dotty com)
# All rights reserved.
#
# Project: mingw-builds ( http://sourceforge.net/projects/mingwbuilds/ )
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
# - Redistributions of source code must retain the above copyright
#     notice, this list of conditions and the following disclaimer.
# - Redistributions in binary form must reproduce the above copyright
#     notice, this list of conditions and the following disclaimer in
#     the documentation and/or other materials provided with the distribution.
# - Neither the name of the 'mingw-builds' nor the names of its contributors may
#     be used to endorse or promote products derived from this software
#     without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
# A PARTICULAR PURPOSE ARE DISCLAIMED.
# IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY
# DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
# OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
# OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE
# USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#

# **************************************************************************

function func_absolute_to_relative {
	# $1 - first path
	# $2 - second path
	
   local _common=$1
   local _target=$2
   local _back=""

   while [[ "${_target#$_common}" == "${_target}" ]]; do
      _common=$(dirname $_common)
      _back="../${_back}"
   done

   echo "${_back}${_target#$_common/}"
}

# **************************************************************************

# download the sources
function func_download {
	# $1 - srcs root path
	# $2 - src dir name
	# $3 - sources type: .tar.gz, .tar.bz2 e.t.c...
	#      if sources get from a repository, choose it's type: cvs, svn, hg, git
	# $4 - URL
	# $5 - log file name
	# $6 - marker file name
	# $7 - revision

	[[ -z $4 ]] && {
		echo "URL is empty. terminate."
		exit 1
	}

	local _WGET_TIMEOUT=5
	local _WGET_TRIES=10
	local _WGET_WAIT=2
	local _result=0

	[[ $3 == cvs || $3 == svn || $3 == hg || $3 == git ]] && {
		local _lib_name=$1/$2
	} || {
		local _lib_name=$1/$2$3
	}

	[[ ! -f $6 ]] && {
		echo -n "--> download..."
		case $3 in
			cvs)
				local _prev_dir=$PWD
				cd $1
				[[ -n $7 ]] && {
					cvs -z9 -d $4 co -D$7 $2 > $5 2>&1
				} || {
					cvs -z9 -d $4 co $2 > $5 2>&1
				}
				cd $_prev_dir
				_result=$?
			;;
			svn)
				[[ -n $7 ]] && {
					svn co -r $7 $4 $_lib_name > $5 2>&1
				} || {
					svn co $4 $_lib_name > $5 2>&1
				}
				_result=$?
			;;
			hg)
				hg clone $4 $_lib_name > $5 2>&1
				_result=$?
			;;
			git)
				git clone $4 $_lib_name > $5 2>&1
				_result=$?
			;;
			*)
				[[ ! -f $6 && -f $_lib_name ]] && rm -rf $_lib_name
				wget \
					$4 -O $_lib_name > $5 2>&1
				_result=$?
			;;
		esac

		[[ $_result == 0 ]] && { echo " done"; touch $6; } || { echo " error!"; }
	} || {
		echo "---> downloaded"
	}
	return $_result
}

# **************************************************************************

# uncompress sources
function func_uncompress {
	# $1 - srcs root path
	# $2 - name
	# $3 - ext
	# $4 - marker file name
	# $5 - log file name

	local _result=0
	local _unpack_cmd

	[[ $3 == .tar.gz || $3 == .tar.bz2 || $3 == .tar.lzma \
	|| $3 == .tar.xz || $3 == .tar.7z || $3 == .7z ]] && {
		[[ ! -f $4 ]] && {
			echo -n "--> unpack..."
			case $3 in
				.tar.gz) _unpack_cmd="tar xvf $1/$2$3 -C $1 > $5 2>&1" ;;
				.tar.bz2) _unpack_cmd="tar xvjf $1/$2$3 -C $1 > $5 2>&1" ;;
				.tar.lzma|.tar.xz) _unpack_cmd="tar xvJf $1/$2$3 -C $1 > $5 2>&1" ;;
				.tar.7z) echo "unimplemented. terminate."; exit 1 ;;
				.7z) _unpack_cmd="7za x $1/$2$3 -o$1 > $5 2>&1" ;;
				*) echo " error. bad archive type: $3"; return 1 ;;
			esac
			eval ${_unpack_cmd}
			_result=$?
			[[ $_result == 0 ]] && { echo " done"; touch $4; } || { echo " error!"; }
		} || {
			echo "---> unpacked"
		}
	}
	return $_result
}

# **************************************************************************

# execute list of commands
function func_execute {
	# $1 - execute dir
	# $2 - src dir name
	# $3 - message
	# $4 - commands list

	msg=$3
	local _result=0
	local -a _commands=( "${!4}" )
	declare -i _index=${#_commands[@]}-1
	#local _cmd_marker_name=$THIS_BUILDBASE/exec-$_index.marker

   #[[ -f $_cmd_marker_name ]] && {
		#echo "---> executed"
		#return $_result
   #}
   #_index=0

   #[[ ${#_commands[@]} > 0 ]] && {
		#printf "--> $msg\n"
   #}

   for it in "${_commands[@]}"; do
    #echo got ${it}
		_cmd_marker_name=$THIS_BUILDBASE/exec-$exec_index.marker
		local _cmd_log_name=$THIS_LOGBASE/exec-$exec_index.log

      #[[ ! -f $_cmd_marker_name ]] && {
      {
    	   #echo do ${it}

 					if [ -d $1/$2 ]; then
          	( cd $1/$2 && eval ${it} > $_cmd_log_name 2>&1  )
         	else
           	eval ${it} > $_cmd_log_name 2>&1 
         fi

         _result=$?
         [[ $_result != 0 ]] && {
            echo "error! ${it}"
            return $_result
         } || {
            touch $_cmd_marker_name
         }
      }

      ((exec_index++))
   done

   return $_result
}

# **************************************************************************

# apply list of patches
function func_apply_patches {
	# $1 - srcs dir name
	# $2 - src dir name
	# $3 - list

	local _result=0
	_index=0
	local -a _list=( "${!3}" )
	[[ ${#_list[@]} == 0 ]] && return 0

	((_index=${#_list[@]}-1))
	[[ -f $1/$2/_patch-$_index.marker ]] && {
		echo "---> patched"
		return 0
	}
	_index=0

	[[ ${#_list[@]} > 0 ]] && {
		echo -n "--> patching..."
	}

	for it in ${_list[@]} ; do
		local _patch_marker_name=$1/$2/_patch-$_index.marker
		[[ ! -f $_patch_marker_name ]] && {
			( cd $1/$2 && patch -p1 -i $PATCH_DIR/${it} > $THIS_LOGBASE/patch-$_index.log 2>&1 )
			_result=$?
			[[ $_result == 0 ]] && {
				touch $_patch_marker_name
			} || {
				_result=1
				break
			}
		}
		((_index++))
	done

	[[ $_result == 0 ]] && echo "done" || echo "error!"
	return $_result
}

# **************************************************************************

# configure
function func_configure {
	# $1 - name
	# $2 - src dir name
	# $3 - flags
	# $4 - log file name

	local _marker=$THIS_BUILDBASE/$this_name_configure.marker
	local _result=0

	[[ ! -f $_marker ]] && {
		echo -n "--> configure..."
		( cd $THIS_BUILDBASE && eval $( func_absolute_to_relative $THIS_BUILDBASE $SRCS_DIR/$2 )/configure "${3}" > $4 2>&1 )
		_result=$?
		[[ $_result == 0 ]] && {
			echo " done"
			touch $_marker
			return $_result
		} || {
			echo " error!"
			return $_result
		}
	} || {
		echo "---> configured"
	}

	return $_result
}

# **************************************************************************

# make
function func_make {
	# $1 - name
	# $2 - src dir name
	# $3 - command line
	# $4 - log file name
	# $5 - text
	# $6 - text if completed

	local _marker=$THIS_BUILDBASE/_$6.marker

	local _result=0

	[[ ! -f $_marker ]] && {
		echo -n "--> $5"
		( cd $THIS_BUILDBASE && eval ${3} > $4 2>&1 )
		_result=$?
		[[ $_result == 0 ]] && { echo " done"; touch $_marker; } || { echo " error!"; }
	} || {
		echo "---> $6"
	}
	return $_result
}

# **************************************************************************

function run_test {
	# $1 - executable name
	# $2 - sources names
	# $3 - tests dir

	local _result=0
	local -a _list=( "${!2}" )

	[[ $USE_MULTILIB == no ]] && {
		[[ $ARCHITECTURE == x32 ]] && {
			local -a _archs=(32)
		} || {
			local -a _archs=(64)
		}
	} || {
		local -a _archs=(32 64)
	}

	for arch_it in ${_archs[@]}; do
		[[ ! -f $3/$arch_it/$1.marker ]] && {
			for src_it in "${_list[@]}"; do
				local _first=$(echo $src_it | sed 's/\([^ ]*\).*/\1/' )
				local _prev=$( echo $src_it | sed '$s/ *\([^ ]* *\)$//' )
				local _last=$( echo $src_it | sed 's/^.* //' )
				local _cmp_log=$3/$arch_it/$_first-compilation.log
				local _run_log=$3/$arch_it/$_first-execution.log

				printf "%-50s" "--> $([[ ${_prev%% *} =~ .cpp ]] && echo -n G++ || echo -n GCC) compile $arch_it: \"$_first\" ... "
				[[ ${_prev%% *} =~ .cpp ]] && {
					echo "g++ -m${arch_it} $COMMON_CXXFLAGS $COMMON_LDFLAGS $TESTS_DIR/$_prev $3/$arch_it/$_last" > $_cmp_log
					( cd $3/$arch_it && g++ -m${arch_it} $COMMON_CXXFLAGS $COMMON_LDFLAGS $TESTS_DIR/$_prev $3/$arch_it/$_last >> $_cmp_log 2>&1 )
				} || {
					echo "gcc -m${arch_it} $COMMON_CXXFLAGS $COMMON_LDFLAGS $TESTS_DIR/$_prev $3/$arch_it/$_last" > $_cmp_log
					( cd $3/$arch_it && gcc -m${arch_it} $COMMON_CFLAGS $COMMON_LDFLAGS $TESTS_DIR/$_prev $3/$arch_it/$_last >> $_cmp_log 2>&1 )
				}
				_result=$?
				[[ $_result == 0 ]] && {
					echo "-> $_result -> done"
				} || {
					echo "-> $_result -> error. terminate."
					[[ $SHOW_LOG_ON_ERROR == yes ]] && $LOGVIEWER $_cmp_log
					exit $_result
				}
				[[ $_last =~ .exe ]] && {
					printf "%-50s" "--> execute     $arch_it: \"$_last\" ... "
					( cd $3/$arch_it && $_last > $_run_log 2>&1 )
					_result=$?
					[[ $_result == 0 ]] && {
						echo "-> $_result -> done"
					} || {
						echo "-> $_result -> error. terminate."
						[[ $SHOW_LOG_ON_ERROR == yes ]] && $LOGVIEWER $_run_log
						exit $_result
					}
				}
			done

			touch $3/$arch_it/$1.marker
		} || {
			echo "---> test $arch_it: \"$1\" - passed"
		}
	done
}

# **************************************************************************

function check_result {
	_result=$1
	logfile=$2
	[[ $_result != 0 && 
        $SHOW_LOG_ON_ERROR == yes && -e $logfile ]] && {
		 $LOGVIEWER $logfile
       }
     	return $_result
}

# **************************************************************************
